name: productivejournal
description: A Project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  beamer: ^1.4.0+1
  bloc: ^8.0.3
  cupertino_icons: ^1.0.4
  equatable: ^2.0.3
  flex_color_scheme: ^4.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_hooks: ^0.18.2+1
  flutter_localizations:
    sdk: flutter
  formz: ^0.4.1
  get_it: ^7.2.0
  http: ^0.13.4
  intl: ^0.17.0
  logger: ^1.1.0
  responsive_builder: ^0.4.2
  responsive_framework: ^0.1.7
  table_calendar: ^3.0.4

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
